configurator/src/main/java/com/devonfw/ide/configurator/Configurator.java, configurator/src/main/java/com/devonfw/ide/configurator/logging/Log.java, configurator/src/main/java/com/devonfw/ide/configurator/merge/DirectoryMerger.java, configurator/src/main/java/com/devonfw/ide/configurator/merge/PropertiesMerger.java, configurator/src/main/java/com/devonfw/ide/configurator/resolve/VariableResolverImpl.java
After refactoring inverse merge (`update-eclipse-workspace-settings`) was broken. Some variables were not substituted anymore. To trace down the error I improved the logging that was not yet helpful enough. Further I discovered that on linux and mac the system resolves links (which are especially required to make eclipse work under macos) and therefore the re-substitution of the paths does not work as expected. I extended the solution to resolve symbolic links and allow also the substitution of the results as far as symlinks are involved.
=> Fixed inverse merge, improved logging during debugging

scripts/src/main/resources/scripts/functions
```
Could not create local repository at /.m2/repository
```
Reason: `DEVON_HOME_DIR` variable set and resolved to late in `functions`.
=> #50: fixed bug in home resolution

scripts/src/main/resources/system/windows/power-shell/devon-power-shell.reg
=> #198: fixed powershell integration

documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/devon
* fix for #229 eclipse always launched in main workspace
=> #229: fixe to preserve workspace that was reset to main

404.html, index.html, oomph/.project, oomph/index/org.eclipse.setup, oomph/products/DevonIde.setup, oomph/products/catalog_devonfw.setup, oomph/products/changelog.adoc, oomph/projects/DevonIde.setup, oomph/projects/catalog_devonfw.setup
This repository has been renamed from `devon-ide` to `ide`. This has broken our CobiGen Oomph installer as the URLs are not correct.
This PR fixes this issue.
=> Renaming URLs to correct repo name

documentation/jenkins.asciidoc
The command `add-ci` doesn't exist anymore, it has been renamed to `add`.
=> Updated Jenkins add command syntax in the documentation

.travis.yml
- Branch changed to master as it is the default branch
- OpenJDK 8 removed
=> Travis CI configuration fixed

documentation/conf.asciidoc, documentation/configurator.asciidoc, documentation/eclipse.asciidoc, documentation/features.asciidoc, documentation/ide.asciidoc, documentation/scripts.asciidoc, documentation/settings.asciidoc, documentation/setup.asciidoc, documentation/software.asciidoc, documentation/structure.asciidoc, documentation/usage.asciidoc, documentation/variables.asciidoc, documentation/workspaces.asciidoc
Most if not all of those typos had been identified by `Spell Right` extension from Bartosz Antosik within VS Code. I have used it on macOS, where Spell Right uses the system spelling API
Link: https://github.com/bartosz-antosik/vscode-spellright
License:  [MIT License](https://github.com/bartosz-antosik/vscode-spellright/blob/master/LICENSE.md)
=> Fix typos inside documentation.

scripts/src/main/resources/scripts/command/cicdgen, scripts/src/main/resources/scripts/command/node
Fixed a bad conditional in the cicdgen installation.
Also, in order to be sure that the devon4node installation is using the npm inside the IDE, I added the lines to install & use npm that other commands are already using.
=> Solved problems with cicdgen & devon4node installation

documentation/cli.asciidoc, documentation/cobigen.asciidoc, scripts/src/main/resources/scripts/command/cobigen, scripts/src/main/resources/scripts/functions
For issue #59: 
* added (minimal) documentation
* support for extracting *.jar files in `doExtract`
* support for unzipping crappy *.zip or *.jar files that contain the exact same file multiple times without prompting the user with confusing questions
* set executable flags so it also works on MacOS and Linux
* prepared for future releases to be installed with ability to update
=> #59: improved cobigen-cli

scripts/src/main/resources/scripts/command/eclipse
Fix for #346 
(I could have just swapped $1 and $2 but to avoid confusion and for maintenance I changed it properly).
=> #346: fixed eclipse add-plugin

scripts/src/main/resources/scripts/devon.bat
Non-Admin installations of GitForWindows and Cygwin change the registry under hive HKEY_CURRENT_USER, not HKEY_LOCAL_MACHINE.
Looping over both hives - with user hive as second - will detect also non-admin installation. If both exist, the user installation gets priority.
The current implementation always searches for both machine and user level setup inside registry. If the number of registry read shall be minimized the script would need to be rewritten accordingly.
=> #343: Detect non-admin GitForWindows and Cygwin

scripts/src/main/resources/scripts/command/ide
Without this patch `devon ide update projects` failed if the SETTINGS/projects directory was not available. This would brake setup for existing projects which are not aware of this feature.
So we should definitly merge this fix before releasing the new feature.
=> Do not file if SETTINGS/project is not existing

documentation/projects.asciidoc, scripts/src/main/resources/scripts/command/ide
Proposal to fix https://github.com/devonfw/ide/issues/372
Users have to provide params for the build command (e.g. dependency:go-offline to just download libs). Without params build is skipped.
=> Rework build on import

scripts/src/main/resources/scripts/command/mvn
And again a fix for #390 (maven is really a strange tool and was otherwise executing project tests in devonfw-ide itself when `org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate` was called.
=> #390: prefer ci-friendly .mvn/maven.config if present for get-version

configurator/src/main/java/com/devonfw/tools/ide/configurator/merge/JsonMerger.java
Currently, merging settings.json file, which contains json values `true`, `false`, or `null` will result in an installation, which is not able to merge settings.json of vscode and the user is therefore not able to start vscode even.
This fix implements the jsonmerger to cover all json node types.
=> fix jsonmerge for boolean and null values

scripts/src/main/resources/scripts/environment-project.bat
Fix for #395 and replacement for PR #426
=> #395: windows fix for variables containing whitespaces or quotes

scripts/src/main/resources/scripts/functions
Avoid variable value like "7+1" and resolve the arithmetic expansion already within this first reassignment to variable i.
=> Use explicit arithmetic expansion

documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/build, scripts/src/main/resources/scripts/command/cicdgen, scripts/src/main/resources/scripts/command/cobigen, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/help, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/ionic, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/ng, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/npm, scripts/src/main/resources/scripts/command/project, scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/command/sonar, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/command/yarn, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/environment-project.bat, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/setup.bat
for #261
Variable renamed to start with DEVON_ (not DEVONFW_) in order to not introduce another namespace prefix.
The trigger line could also be moved into `functions` instead  (for most scripts) - but then the call of `functions` itself would not be traced - which makes it harder to read the generated trace logs.
=> Add DEVON_IDE_TRACE to scripts

CHANGELOG.asciidoc, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
Implements #449 (update devon4j to `2020.08.001`).
ATTENTION: PR travis build will fail unless `devon4j` release is available in maven central.
=> #449: update devon4j version to 2020.08.001

scripts/src/main/resources/scripts/command/npm, scripts/src/main/resources/scripts/command/yarn, scripts/src/main/resources/scripts/functions
=> #431: fixed build command

scripts/src/main/resources/scripts/command/node
Fix quoting of args in array context.
Use "$@" instead of "$*" for correct quoting of each single command option. Otherwise "devon node" can't take more than one argument.
=> Fix args quoting for node commandlet

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/intellij
currently intellij support does not work properly on linux as `idea` command can not be found (on linux the executable is `idea.sh`). We should therefore normalize this as done for other tools and platforms.
=> make intellij work on linux (idea.sh vs. idea)

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/intellij
add `IDEA_HOME/bin` to `PATH` after installation as otherwise `command -v idea` will fail.
=> add IDEA_HOME to PATH after installation

scripts/src/main/resources/scripts/command/vscode
Fixes bug issue #479 by renaming function aligned with `eclipse` commandlet for better maintainability.
=> #479: fixed add plugin via CLI

scripts/src/main/resources/scripts/command/ng, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/npm
Fixes bug issue #483 and ensures that `node`, `npm` and `ng` are always taken from `devonfw-ide` sandbox installtion avoiding side effects from global installations.
=> #483: fixed node tool installations

configurator/src/main/java/com/devonfw/tools/ide/configurator/SortedProperties.java, configurator/src/test/java/com/devonfw/tools/ide/configurator/SortedPropertiesTest.java
=> #470: make SortedProperties sorting on store

CHANGELOG.asciidoc, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
=> #522 :update devon4j to 2020.12.002

scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-setup
Fixes #536.
Besides stopped downgrading Java to 1.8 in integration tests as tools such as Eclipse do not support this version anymore.
=> #536: safe downloads

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
WIP for #545 (devon4j not yet released, ide-settings not yet updated: https://github.com/devonfw/ide-settings/blob/master/eclipse/archetype-catalog.xml#L9).
=> #545: migrations for devon4j 2021.04.001

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/devon.properties
=> #557: minimize tools on setup

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/jenkins
=> devonfw/ide#414: eclipse plugin tracker

CHANGELOG.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/devon.properties
implements #513:
* instead of hardcoding the creation of IDE start scripts this is now configurable via new variable `DEVON_CREATE_START_SCRIPTS`
* the start scripts are created after project imports with `--all` option so all workspaces are considered#
* documentation and changelog was updated
=> #513: create start scripts

scripts/src/main/resources/scripts/command/node
=> #601: update nodejs default version from 14.17.3 to 14.17.6

scripts/src/main/resources/scripts/command/cobigen
as it is done with --verbose it does not make any sense and it's not working as expected
=> There is no doIsQuiet yet for CobiGen

documentation/eclipse.asciidoc, documentation/intellij.asciidoc, documentation/java.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java
* implements #678
* includes doc update of variables
* includes support in `java` commandlet (fully tested)
* includes support in `eclipse` commandlet (fully tested)
* includes support in `intellij` commandlet
* includes doc updates for `java`, `eclipse` and `intellij`
* settings already updated to enforce proper JRE is set as default in new Eclipse workspace
=> #678: support for EXTRA_JAVA_VERSION

scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/environment-project.bat
Improvement for #678: do not add `extra` to path.
Side-note: On MacOS for Java a workaround is needed:
* java follows MacOS app conventions but not standards of other OS
* that is has a folder `Contents` that contains subfolders `Home` and `MacOS`
* the expected layout of a JDK is within `Contents/Home` that also contains the `bin` folder that contains `java`, etc.
* However, the entire structure is required for the JDK to work
* as a workaround devonfw-ide detects this and then renames the `java` folder to `jdk` and creates a symlink `java` pointing to `jdk/Contents/Home` so everthing else works as expected.
* as a result also the `jdk` folder is put on the `PATH`. This does not cause real harm but it should also be prevented.
* Further we have the same issue also with other apps on …
=> #678: prevent to add extra to path

scripts/src/main/resources/scripts/functions
In the source of scripts for devonfw-ide we use expressions like `$[devon_ide_version]` that are resolved during the build of a release.
https://github.com/devonfw/ide/blob/eaf71f85e6ac2346aa9dcce983d0e03adb505015/scripts/src/main/resources/scripts/command/ide#L47
Sometimes developers or early adopters might use the original scripts for testing. In such case bash will evaluate this expression to `0`. As a result in this case a command like `devon ide update scripts` does nothing at all (no output, no update).
This can be very confusing for users that end up in this situation though it may only affect very few people.
However, already for myself (in my ide for devonfw itself I use symlinks to the latest source scripts) it is nice and easy to solve that we get a little more output and also …
=> improve updates for developers

scripts/src/main/resources/scripts/devon.properties
Adresses: https://github.com/devonfw/cobigen/issues/1430 and implements #696
=> #696 added new COBIGEN_HOME environment variable to devon.properties

scripts/src/main/resources/scripts/command/docker
=> fix docker setup for windows

documentation/LICENSE.asciidoc, documentation/cli.asciidoc, documentation/devonfw-ide-usage.asciidoc, documentation/scripts.asciidoc, documentation/terraform.asciidoc, scripts/src/main/resources/scripts/command/docker, scripts/src/main/resources/scripts/command/terraform
Files to integrate terraform installation into devonfw IDE
=> #637 Terraform integration

scripts/src/main/resources/scripts/functions
With #641 we introduced mirrors repo with flexible configuration to build download URLs.
However, we still face tools/products that do not follow best-practices and build kind of exotic URLs that are not structured logically using a simple pattern.
As a workaround when filenames or URL paths differ per OS we want to support that instead of putting variables like `${version}`, `${arch}` or `${ext}` into URLs we put them into `os-mappings` if required so that you can build the URL or filename dependent on the operating system. E.g. Rancher-Desktop is a candidate that includes architecture (`${arch}`) in MacOS releases while they are omitted for linux and windows, etc.
We have to be aware that with previous releases of devonfw-ide this change does not apply and using it in mirrors could …
=> replace ${os} first for flexibility

scripts/src/main/resources/scripts/command/helm, scripts/src/main/resources/scripts/command/terraform
when terraform and helm are used as proxy commandlets in devonfw-ide the arguments are not properly passed and as a result it is not working:
```
The Kubernetes package manager
Common actions for Helm:
- helm search:    search for charts
- helm pull:      download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts
...
```
so the `env` parameter is not passed to `helm`. Same problem exists for `terraform`.
=> bugfix terraform and helm

scripts/src/main/resources/scripts/command/dotnet
See #781: With PR #292 an unwanted dependency from DotNet to Java has been introduced.
I assume this was just copied & pasted from another commandlet.
As DotNet does not depend on Java there is no sense in this so I simply removed it.
=> #781: removed pointless java dependency from dotnet

CHANGELOG.asciidoc, scripts/src/main/resources/setup.bat
=> #921: fixed setup.bat

documentation/functions.asciidoc, scripts/src/main/resources/scripts/functions
Small fixes and improvements to changes from #826 and part of #933:
* when extracting `doUpdateMirrors` I also extracted the `mirrors_dir` variable what caused some confusing errors discussed in #933 - see PR #934 that will receive an upstream fix with this PR after merge.
* when `devon «tool» version list` is performed or `devon «tool» version set latest` is performed, the mirrors git needs to be cloned and up-to-date what was missing in #826 
* after `devon «tool» version set «version»` I now output a hint to the user to run setup to actually do the installation
=> #847: #826: fixes

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/dotnet
The nightly test showed us an error after the dotnet installation. While analysing the error, I realised that there is something like a loop so that the github runner comes to `segmentation fault` error.  This PR fixes this bug.
More details can be found in related issue: https://github.com/devonfw/ide/issues/974
=> #974: Fixed dotnet command for nightly test 

scripts/src/test/bash/integration-test-vscode
This PR fixed the nightly test for vscode. The nightly test failed, because the devonfw-extension-pack plugin was installed automatically and reached the timeout of github actions.
This fix belongs to related issue: https://github.com/devonfw/ide/issues/887
A new issue: [982](https://github.com/devonfw/ide/issues/982) was created to extend the vscode commandlet so that the workaround is no longer necessary.
=> #887: Temporary fixed vscode nightly test

scripts/src/main/resources/scripts/devon.bat
- add pause before goto :eof to prevent terminal from closing immediately (if git bash is not installed)
- add new subroutine called "git_installation". This allows git for windows installation conditions to be executed/checked.
=> #1005: update devon.bat to show bash error

CHANGELOG.asciidoc, documentation/LICENSE.asciidoc, documentation/cli.asciidoc, documentation/devonfw-ide-usage.asciidoc, documentation/gcloud.asciidoc, documentation/scripts.asciidoc, scripts/src/main/resources/scripts/command/gcloud
GCloud CLI is added to the ide as a commandlet. It only works for Windows systems as it requires Python to run. After Python is fixed for MacOS and Linux, we can update this command. 
Related issue: #1004
=> #1004: GCloud CLI integration for windows

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/gcviewer, scripts/src/test/bash/test-functions-doc
Functions in commandlets are now checked to have a decleration either in the same file or in one of the devon function files!
Tested it and it already found one function that missed the "function" keyword. I didn't even know before that you could define functions without the function keyword 😄
=> #939: extending test functions doc to check for invocation of undeclared functions

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/functions, scripts/src/test/bash/integration-test-custom-tools
This PR fix the behaviour of `doReplaceExtractedSkipSingleFolder` on MacOS system without M1 chips. The reason of the bug was that `wc-w` may produce leading spaces,
Related issue: #1052
=> #1052: Fix leading spaces on macOS

CHANGELOG.asciidoc, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
Update devon4j to 2023.01.001 | submodules and migrations
Related issue: https://github.com/devonfw/ide/issues/1062
=> #1062: Update devon4j to 2023.01.001

documentation/functions.asciidoc, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
#1054 automated security warnings
=> #1054 automated security warnings

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/androidstudio/AndroidJsonDownload.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/androidstudio/AndroidJsonItem.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/androidstudio/AndroidStudioUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/docker/DockerDesktopUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/docker/DockerRancherDesktopUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/dotnet/DotNetUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/eclipse/EclipseUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/gh/GhUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/graalvm/GraalVmUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/helm/HelmUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/kotlinc/KotlincNativeUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/lazydocker/LazyDockerUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/node/NodeUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/npm/NpmUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/terraform/TerraformUrlUpdater.java, url-updater/src/test/java/com/devonfw/tools/ide/integrationtests/AndroidStudioUrlUpdaterMock.java
Addresses/Fixes: #1162 
Implements:
* added first implementation of download URL and checksum extraction from version json
* fixed updateStatusJson (can now handle initial URL generate using update false)
* cleaned up AndroidStudioUrlUpdater and test mock
* added AndroidJsonDownload
* added download to AndroidJsonItem
* removed duplicated doAddVersion method (added check for checksum param instead)
* added new checksum param to doAddVersion (defaults to empty string)
* updated javadocs
* added links to javadocs
=> #1162 android studio json urls

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/npm/NpmUrlUpdater.java
partially solving #1142 
- fixed the wrong url, which was used for the npm baseURL
- changed the Version pattern, so to not include non existing npm versions.
=> #1142 wrong checksum in ide urls for npm 

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/gradle/GradleUrlUpdater.java
Addresses/Fixes: #1218 
Implements:
* made version regex pattern more distinct
* added hashsum param to doAddVersion
* added doGetHashSumForVersion method (can extract a valid hashsum for a given version)
* moved regex patterns and URLs into constants
* added lazy loading of responseBody
* added extra check for empty checksum
* moved download Url into constant
=> #1218: optimized gradle url-updater

scripts/src/main/resources/scripts/functions
Addition to #1084:
Omit the default edition to keep behavior of previous releases of devonfw-ide.
Small change, big impact: This allows to reuse the download cache and prevents that devonfw-ide will download all the existing files again and create duplicates on the disc.
=> #1084: omit default edition in the download filename

scripts/src/main/resources/scripts/command/pip
Addition to https://github.com/devonfw/ide/issues/1084:
Omit the default edition to keep behavior of previous releases of devonfw-ide.
Small change, big impact: This allows to reuse the download cache and prevents that devonfw-ide will download all the existing files again and create duplicates on the disc.
This is coded in pip commandlet, and must be fixed, too
=> #1084: omit default edition in the download filename at pip

scripts/src/main/resources/scripts/functions
Seems to fix both #1283 and #1276
=> #1283: #1276: checksum verification only for ide-urls

url-updater/pom.xml, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java
In #1132 with PR #1205 the usage of selenium was removed from the code.
This is a cleanup PR to also remove the now obsolete maven dependencies that are not used anymore since this change.
=> #1132: remove obsolete dependencies

documentation/functions.asciidoc, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/devon.properties, scripts/src/main/resources/scripts/functions
Adresses/Fixes: #1164 
Implements:
* added new JENKINS_HOME environment variable to devon.properties
* renamed JENKINS_HOME in jenkins script to JENKINS_CLI_HOME
* added jenkins home folder creation to doSetup
* added override of java user.home to each java command of jenkins
* added first version of admin password retrieval
* added new param target_filename to doInstall
* added extra condition to doInstall to provide a filename for doDownload
* replaced doDownload in jenkins tool command with doInstall
* adjusted extraction of jenkins-cli.jar in doSetup of jenkins (jenkins-cli.jar was removed from WEB_INF folder in later jenkins versions)
* replaced password with auth file
=> #1164: fix jenkins stop command

ide/src/main/java/com/devonfw/tools/ide/url/updater/gcviewer/GcViewerUrlUpdater.java
#1330 GcViewer DonwloadUrl not Working 
The URL added in #1134 only works, when manually downloading, when using with the ide tool, it downloads meta data and not the desired .jar. Therefore the "old" url must be used, despite being one that will be redirected.
=> #1330 GcViewer DonwloadUrl not Working

ide/src/main/java/com/devonfw/tools/ide/commandlet/ToolCommandlet.java, ide/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, ide/src/main/java/com/devonfw/tools/ide/context/IdeContextConsole.java, ide/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java, ide/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java, ide/src/main/java/com/devonfw/tools/ide/process/ProcessErrorHandling.java, ide/src/main/java/com/devonfw/tools/ide/process/ProcessResult.java, ide/src/main/java/com/devonfw/tools/ide/process/ProcessResultImpl.java
Improvements for #1090:
* added `ProcessResult`
* improved `ProcessContext` API, run "mvn.cmd" instead of "mvn", etc.
* fixed `IdeContext.readLine()` if console is not available.
* fixed `AbstractIdeContext.question`
=> #1090: improve ProcessContext, fixed readLine

documentation/android-studio.asciidoc, documentation/intellij.asciidoc, scripts/src/main/resources/scripts/command/android-studio, scripts/src/main/resources/scripts/command/intellij
Addresses/Fixes: #1358 
Implements:
* added check for new DISABLE_WORKSPACE environment variables to intellij and android-studio
* added documentation for DISABLE_WORKSPACE environment variables to intellij and android-studio
=> #1358: implemented disable workspace functionality

scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-version-compare
Fixes #1367. Added small clause to `doVersionCompare()` to make version like `21_35` smaller than `21.0.1_12`.
=> #1367: added fix to java version compare

documentation/functions.asciidoc, scripts/src/main/resources/scripts/functions
Closes #1369. To select the latest version (even unstable), one can pass \*! or something like 1.2*!
=> #1369: added latest stable version pattern

.gitattributes, scripts/src/main/resources/scripts/functions
fixes #1391
filter for directories when searching/resolving versions.
=> #1391: avoid files like dependencies.json are considered as version
