devonfw/ide

scripts/src/main/resources/TERMS_OF_USE.adoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/help, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/environment-project.bat, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/setup, scripts/src/main/resources/setup.bat, settings/src/main/settings/devon/conf/variables, settings/src/main/settings/devon/conf/variables.bat, settings/src/main/settings/devon/variables, settings/src/main/settings/devon/variables.bat, settings/src/main/settings/ide-properties, settings/src/main/settings/ide-properties.bat
Furhter improvements to complete #31
=> #31: added setup script, improved/fixed others

scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
=> windows fix

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/devon.properties, scripts/src/main/resources/scripts/environment-project.bat, scripts/src/main/resources/scripts/functions, settings/src/main/settings/intellij/workspace/update/idea.properties
=> #45: intellij setup works on macos

scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
=> #73: fixe for load_properties in bash

scripts/src/main/resources/scripts/command/build, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/help, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/ng, scripts/src/main/resources/scripts/command/npm, scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/command/yarn, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
imrpoves/fixes:
* #53 release support
* #82 yarn support
* #83 npm support
=> #53: improved release support

scripts/src/main/resources/scripts/functions
=> #90: fix for ide scripts on windows

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/functions
* #93: fixed installer
* #92: fixed update
* also improved that `devon -v` is working if not sourced (e.g. on `./scripts/devon -v`).
=> #93: fixed installation logic

documentation/software.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/functions
* #110: fixed URL part, software version upgrade
* #98: ability to configure DEVON_SOFTWARE_REPOSITORY
* #109: updated vscode
=> Improved software download, installation, and upgrading

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
=> #116: fixed setup

scripts/src/main/resources/scripts/environment-project
=> #89: fixed command not found error

.travis.yml, scripts/src/main/resources/scripts/functions
fixed bug that @vapadwal found in #122.
=> #122: fixed bug with incomplete download_url if software repo is used

scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project
=> #126: fixed workspace variable setup

.mvn/maven.config, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/release
fixes:
* #133 - devon mvn get-version
* #132 - devon release : push changes
=> #133 fix mvn get-version, #132: release git push

configurator/src/main/java/com/devonfw/tools/ide/configurator/Configurator.java, configurator/src/main/java/com/devonfw/tools/ide/locking/EclipseWorkspaceLockChecker.java, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/functions
=> #41: check if eclipse ws is locked and #136: fixed configurator jar version problem

scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/devon.properties
=> #54: added node commandlet and node.js support

scripts/src/main/resources/scripts/command/ide
=> #100: warning/abort on space in path

scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/functions
=> #131: improve next_version and detect fork

scripts/src/main/resources/scripts/functions
fixes:
* #143 fatal update error
* bug that wrong parameter was used to output installed software
=> #143: fixed fatal update bug

scripts/src/main/resources/scripts/command/vscode
*devon vscode create-script* command was creating eclipse scripts instead of vscode.
=> Updated vscode command/script

documentation/configuration.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/environment-project.bat, scripts/src/main/resources/scripts/functions
* #151 support for ~/devon.properties
* #153 allow to rerun release build
* #140 complete tools update support
* update to maven 3.6.1
=> enhancements

documentation/software.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/functions
* #152: added local software path feature
* #151: fix for commandlet invocations so un-exported variables remain visible
* #145: fix for doUpgradeMavenArtect invoking doInstall (was forgotten on refactoring)
=> #152: added local software path feature

scripts/pom.xml, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/setup, scripts/src/test/bash/all-tests, scripts/src/test/bash/test-setup
Lets see how travis handles IDE GUIs popping up ;=)
=> #157: added integration testing

configurator/src/main/java/com/devonfw/tools/ide/migrator/MigrationImpl.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrator.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/file/FileMigration.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/xml/MavenPropertyReplacement.java, configurator/src/test/java/com/devonfw/tools/ide/migrator/MigrationsTest.java, documentation/java.asciidoc, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/setup, scripts/src/test/bash/all-tests, scripts/src/test/bash/test-setup, settings/src/main/settings/eclipse/archetype-catalog.xml
* #159 improved/fixed devon4j migration
* #160: switched from OpenJDK to AdoptOpenJDK
* #161: fixed mvn invocation and exit code
*  #162: propagate exit code
=> #159: devon4j migration #160: AdoptOpenJDK #161: #162: exit codes

documentation/eclipse.asciidoc, documentation/intellij.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/functions
=> #135: support --all to iterate all workspaces

scripts/src/main/resources/scripts/command/build, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/help, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/ng, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/npm, scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/command/yarn, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/setup, scripts/src/test/bash/test-shellcheck
* #66 bash harmonizing
* #157: shellcheck as integration-test
* #165: workaround for MacOs
=> #66: #157: introduced shellcheck and reworked all issues

scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/functions
* Fixes #169 
* small fix for Java symlink edge-case on MacOS
* improvement for gradle
* clean code
=> #169: improved tar extraction and support .tar.xz

documentation/devon-ide-doc.asciidoc, documentation/features.asciidoc, documentation/java.asciidoc, documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc, documentation/scripts.asciidoc, documentation/settings.asciidoc, documentation/software.asciidoc, pom.xml
* documentation for #173
* some doc cleanup/fixes
=> #173: ide migration guide

documentation/setup.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/environment-project.bat
* fixes #193: windows setup fails
* fixes #180: eclipse start window
* fixes #177: duplicate warnings on setup
=> #193: windows fix

README.adoc, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/system/windows/README.adoc, scripts/src/main/resources/system/windows/power-shell/devon-power-shell.reg, scripts/src/test/bash/test-version-compare
* #178: no admin rights also for uninstall
* #199: fixes for uninstall
* #200: update devon.bat if newer
* #198: power-shell improvements (bug still present!)
* #203: MacOS workaround for cp -u
* #202: fixed version compare, added tests
=> Various fixes and improvements

documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc, documentation/setup.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
* #84: install all cobigen plugins via proper extension IDs
* #190: upgrade support from oasp4j-ide
* #196: fixed prerequisites in documentation
* #204: fixed eclipse startup script for MacOS
=> #84: #190: #196: #204: fixes and improvements

scripts/src/main/resources/scripts/devon.bat
=> #206: workaround for severe windows CMD/BAT bug

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/setup.bat, scripts/src/main/resources/system/windows/devon-uninstall.reg
* #209: further fixes and improvements for setup and uninstall
=> #209: windows bashes

scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-version-compare
* #202 additional fix for more specific cases
=> #202: version-compare further improved

scripts/src/main/resources/scripts/command/eclipse
=> #211: correct TM Terminal URL from dhelmke

scripts/src/main/resources/scripts/functions
* #231: fixed download conflict
* #98: fixed extension and improved output
=> #231: repo sub-folder in ~/Downloads

documentation/ide.asciidoc, documentation/software.asciidoc, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/functions
* #224: split update, ask on unstable release, omit software repo for LATEST, omit OS if independent
=> #224: split update, ask on unstable release, omit software repo for LATEST, omit OS if independent

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java, scripts/src/main/resources/scripts/functions
* fixed #238: set extension to .tgz properly for repo.
* fixed #240: workaround for maven archetype-catalog update bug
=> #238: fixed extension

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/environment-project
=> #235: moved devon script update to ide commandlet

scripts/src/main/resources/scripts/environment-project
* fix for #215 (regex was not working properly)
=> #215: bash quoting mess fixed

.gitmodules, README.asciidoc, documentation/Home.asciidoc, documentation/configuration.asciidoc, documentation/configurator.asciidoc, documentation/features.asciidoc, documentation/integration.asciidoc, documentation/license.asciidoc, documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc, documentation/scripts.asciidoc, documentation/settings.asciidoc, documentation/structure.asciidoc, documentation/system.asciidoc, documentation/workspaces.asciidoc, pom.xml, scripts/pom.xml, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/devon.properties, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-version-compare
=> #142: renamed repo, updated all references

documentation/eclipse.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/templates/oomph/mvn.setup, scripts/src/main/resources/scripts/templates/oomph/mvn_clone.setup, scripts/src/main/resources/scripts/templates/oomph/plain.setup, scripts/src/main/resources/scripts/templates/oomph/plain_clone.setup
Rework of the `devon eclipse import «type» [«path/url»]` command.
=> WIP: eclipse-import

scripts/src/main/resources/scripts/command/eclipse
=> #246: updated to eclipse 4.13 (2019-06)

scripts/src/main/resources/scripts/command/eclipse
* also moved `cd ${DEVON_IDE_HOME}` to its respective place (using `pushd/popd` instead)
=> WIP: added relative path handling for project import

scripts/src/main/resources/scripts/environment-project
fix for #262
avoid process substitution issue with pipe while still removing windows CR chars
=> #262: fixed loading of properties on windows

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
* #277: fixed newline in questions
* #275: fixed scripts update to specific version
=> #275: fixed newline in questions #277: fixed scripts update to specific version

scripts/src/main/resources/scripts/devon.bat
small improvement discussed in #269
=> #269: use slash to source so not accidentally taken from path

README.asciidoc, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/version/VersionIdentifier.java, configurator/src/main/java/com/devonfw/tools/ide/migrator/xml/MavenDependencyAdder.java, documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc
This is PR for https://github.com/devonfw/ide/issues/237
=> revision metadata changes for devon4j

documentation/master-ide.asciidoc
Added master file master-ide.asciidoc. devonfw-guide's master.asciidoc file has to include this one
=> Added master file

TERMS_OF_USE.asciidoc
improved terms of use for #291
=> #291: improved terms for 3rd party

TERMS_OF_USE.asciidoc
=> #291: clarify way of inclusion

documentation/Home.asciidoc, documentation/setup.asciidoc
#291: added temporary announcement note about release clarification
=> #291: added temporary announcement note about release clarification

scripts/src/main/resources/scripts/command/java
=> #304: updated to latest stable JDK11

TERMS_OF_USE.asciidoc, documentation/eclipse.asciidoc, scripts/src/main/resources/scripts/command/eclipse
#291: sorted by inclusion, version of GPL for regextester, removed DevStyle
=> #291: improved terms

scripts/src/main/resources/scripts/devon.properties
=> #311: avoid explicit heap tunings

scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/vscode
- node.js 12.13.1 LTS
- VS Code 1.40.2
=> Updated versions

.travis.yml, scripts/pom.xml
=> #310: skip duplicate tests in travis and honor skipTests variable

documentation/software.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
Fix for #322 
Currently WIP (untested and documentation missing)
=> #322: support for custom tools

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/yarn
=> #281: setup tools transitive/recursive

configurator/src/main/java/com/devonfw/tools/ide/configurator/Configurator.java, configurator/src/test/java/com/devonfw/tools/ide/configurator/ConfiguratorTest.java
=> #259: fix for windows backslash vs. slash issues

scripts/src/main/resources/scripts/command/ide
=> #339: reload config after settings have changed

documentation/devonfw-ide-doc.asciidoc
Improvement to PR #344 for `devonfw-ide-doc.pdf`.
=> improved PDF

documentation/devonfw-ide-usage.asciidoc, documentation/usage.asciidoc
fixed usage for devonfw/devonfw-guide#62
=> devonfw/devonfw-guide#62: fixed usage chapter

scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/vscode
https://nodejs.org/en/blog/vulnerability/february-2020-security-releases/
EDIT: VSCode has been updated too.
=> Updated node LTS version that solves vulnerability

documentation/LICENSE.asciidoc, documentation/configuration.asciidoc, documentation/ide.asciidoc, documentation/projects.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/scripts/lib_script/import.groovy, scripts/src/main/resources/scripts/lib_script/import.xml
Implementaton of automated git checkout and eclipse import
see https://github.com/devonfw/ide/issues/175
=> Implementaton of automated git checkout and eclipse import

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/lib_script/import.xml
=> #175: improvement for import

documentation/projects.asciidoc, scripts/src/main/resources/scripts/command/ide, scripts/src/test/bash/all-tests
Fix or workaround for #175 as m2e is unable to download maven artifacts in a reliable way.
=> #175: ability to build projects before import to workaround m2e download instability

documentation/java.asciidoc
see https://github.com/devonfw/devon4j/pull/227
=> update migrate link to point in devon4j

documentation/java.asciidoc, scripts/src/main/resources/scripts/command/java
update java versions:
* default jdk from `11.0.5` to `11.0.6`
* documentation for jdk8 from `8u222b10` to `8u242b08`
=> update java versions to latest fix releases

scripts/src/main/resources/scripts/command/ide
Fix for #363 and replacement for PR #364
=> #363: do git pull of settings on ide update settings

scripts/src/main/resources/scripts/command/eclipse
This fixes the probelm that eclipse could not be started to import projects for some users on windows.
=> Fix project import on windows

scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/environment-project
=> #375: vscode plugin config from settings

documentation/eclipse.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/eclipse
=> #376: improve eclipse plugin config via properties files

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/environment-project
=> #382: improve project import with doLoadProperties

scripts/src/main/resources/scripts/command/vscode
PR trying to fix #111 and #379
=> WIP: #379: #111: fix vscode to be portable/work in sandbox

scripts/src/main/resources/scripts/command/java
=> #370: downgrade Java to 11.0.5_10

pom.xml
=> #369: fixed flattening/versioning of POMs

scripts/src/main/resources/scripts/devon.bat
=> #343: honor BASH_HOME environment variable as fallback if autodetection fails

scripts/src/main/resources/scripts/command/mvn
Fixed error handling in mvn get-version in the context of #390
=> #390: fixed error handling for get-version

documentation/release.asciidoc, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/release
improve `release` commandlet to support custom args passed to the release build command
=> allow custom args for release

scripts/src/main/resources/scripts/command/intellij
=> #398: fixed idea script location, normalized to bin folder across all OS

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/environment-project, scripts/src/test/bash/test-version-compare
* Fixes #394 
* added release 2020.04.001 to changelog
* added test to ensure 2020.04.001 is properly handled by version compare
=> 2020.04.001 improvenents

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide
This should fix problems when trying to import project into different workspaces then `main`.
=> Fix import into non default workspace

documentation/project.asciidoc, documentation/projects.asciidoc, documentation/scripts.asciidoc, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/project
=> #418: #377: added project commandlet, allow project to be inactive

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
update devonfw-ide to devon4j version `2020.04.002` so that latest archetype is created and migratons (from PR #420) to the latest version apply.
=> update devon4j to 2020.04.002

scripts/src/main/resources/scripts/command/eclipse
=> #413: update default to Eclipse 2020-03

scripts/src/main/resources/scripts/command/intellij
=> #399: detect idea executable with fallbacks like idea64.exe

scripts/src/main/resources/scripts/environment-project
=> #424: only append single newline, remove/ignore CR

scripts/src/main/resources/scripts/command/ide
I've updated the PR according to the suggestions provided for rework.
=> Added script to create a meta file in the users directory after setup

scripts/src/main/resources/scripts/environment-project.bat
Fix for #433 as proposed by @markusschuh
=> #433: fix for variable resolution on windows (prevent title symbol in variable name when export is used)

scripts/src/main/resources/scripts/environment-project
issues with quotes and whitespaces in variable values also on bash (linux/mac/win)
similar to #434 and #430
=> #435: fix variable solution on bash

scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-get-next-version
=> #427: keep leading zeros

documentation/vscode.asciidoc, scripts/src/main/resources/scripts/command/vscode
* Fixes #384 
* Relates to #432 (but does not fix settings update)
* Replaces PR #439
=> #384: vscode plugins

scripts/src/main/resources/scripts/functions
=> #440: exit if moving to backup fails with proper error message

scripts/src/main/resources/scripts/command/intellij
=> #446: fixed doConfigure CNP bug for intellij

configurator/src/test/java/com/devonfw/tools/ide/configurator/ConfiguratorTest.java, configurator/src/test/resources/templates/update/json/settings.json, scripts/src/main/resources/scripts/command/vscode
=> #432: fix to ensure update of existing workspace on vscode start

scripts/src/main/resources/scripts/command/eclipse
Update Eclipse to 2020.06 as default version.
=> update to eclipse 2020.06

.travis.yml
implements devonfw/devon4j#289
=> devonfw/devon4j#289: update travis dist to bionic

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/intellij
=> #475: fixed IntelliJ edition versioning

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/intellij
=> update IntelliJ to 2020.2.1

documentation/configurator.asciidoc, documentation/settings.asciidoc, documentation/usage.asciidoc
Implements issue #415 providing better documentation to customize settings and admin usage.
=> #415: improved documentation for admin usage (customizing settings)

CHANGELOG.asciidoc, configurator/src/test/java/com/devonfw/tools/ide/configurator/SortedPropertiesTest.java
* fix for #471 
* fix for #494 
* added 2020.12.001 to changelog
=> Completion of release 2020.12.001

documentation/ng.asciidoc, scripts/src/main/resources/scripts/command/ng, scripts/src/main/resources/scripts/command/yarn
Implementation for #499: Enable configuration of version for yarn and angular cli (ng)
=> #499: Enable configuration of version for yarn and angular cli (ng)

scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
=> #493: export variables for commandlets

scripts/src/main/resources/scripts/command/java
=> #356: create projects directly in workspace

CHANGELOG.asciidoc, configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java, configurator/src/test/java/com/devonfw/tools/ide/migrator/MigrationsTest.java, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/ng
* Fix for #498 migration to devon4j 2020.12.001
* Updated changelog
=> #498: migration to devon4j 2020.12.001

documentation/eclipse.asciidoc, scripts/src/main/resources/scripts/command/eclipse
=> #507 eclipse edition can be switched by variable

scripts/src/main/resources/scripts/command/java
=> #505: check args for java create and provide helpful error message

scripts/src/main/resources/scripts/command/project
=> #480: export workspace variables to properly import to configured workspace

documentation/LICENSE.asciidoc, documentation/eclipse.asciidoc, scripts/src/main/resources/scripts/command/eclipse
fixes #514 by correcting AnyEditTools update site URL.
=> #514: adjusted AnyEditTools update site URL

scripts/src/main/resources/scripts/functions
=> #511: workaround for bug in git for windows

documentation/advanced-tooling-generic.asciidoc, documentation/mvn.asciidoc, documentation/release.asciidoc, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/release
=> devonfw/ide#523: check snapshot versions from dependencies on release

scripts/src/main/resources/scripts/devon.bat
=> #393: improve windows PATH adoption on initial setup

scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/release, scripts/src/main/resources/scripts/functions
=> #539: support advanced ci friendly maven

scripts/src/main/resources/scripts/command/mvn
=> #550: update maven to 3.8.1

scripts/src/main/resources/scripts/command/mvn, scripts/src/test/bash/test-setup
do not prompt for secrets/variables for default settings for issue #542 as discussed in PR #544.
=> #542: #544: do not prompt for secrets/variables for default settings

scripts/src/main/resources/scripts/command/vscode
=> #553: changed vscode userdata dir to workspace

scripts/src/main/resources/scripts/command/help, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/devon
Some improvements of command autocompletion #287:
- `ls` fix for windows on `devon help`
- install autocompletion if not already installed on `devon ide setup`
=> #287: improvements of command autocompletion

documentation/usage.asciidoc
=> autocompletion added

.mvn/maven.config, configurator/pom.xml, documentation/pom.xml, pom.xml, scripts/pom.xml, settings/pom.xml
=> #548: removed changelist

scripts/src/main/resources/scripts/command/jenkins
=> #565: fixed download directory for jenkins

documentation/pom.xml
updates docgen to 2021.04.001 with some bugfixes included.
=> update docgen to 2021.04.001

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/eclipse, scripts/src/test/bash/test-setup
=> #537: Update eclipse to 2021-03

scripts/src/main/resources/scripts/command/ide
Add script creation for intellij
=> Add script creation for intellij

CHANGELOG.asciidoc, documentation/cli.asciidoc, documentation/devonfw-ide-usage.asciidoc, documentation/jasypt.asciidoc, scripts/src/main/resources/scripts/command/jasypt
implemented #575 including doc and changelog
=> #575: added jasypt commandlet

scripts/src/main/resources/scripts/command/eclipse
=> #581: fixed redundant update-sites

documentation/ide.asciidoc, documentation/usage.asciidoc, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
=> #585: settings with branches

scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/devon-autocomplete
=> #573: improve completion

.github/workflows/sync-docs.yml
Need to add this event to trigger website and guide build automatically on document edit
=> Trigger for updating devonfw-guide and website

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java, scripts/src/main/resources/scripts/command/node
=> #592: update node v14.17.3 to fix CVEs

CHANGELOG.asciidoc, documentation/LICENSE.asciidoc, documentation/docker.asciidoc, documentation/features.asciidoc, documentation/kubectl.asciidoc, documentation/setup.asciidoc, documentation/usage.asciidoc
mark feature #584 (docker/k8s) as experimental in docs so we can create a release and already collect further feedback.
=> #584: marked as experimental

scripts/src/main/resources/scripts/command/eclipse
=> #604 fix url from eclipse plugins

scripts/src/main/resources/scripts/command/eclipse
- Removed osuosl.org mirror
- Use loadbalancer of eclipse's download button instead
Fixes #616
=> #616: Updated eclipse mirror

scripts/src/main/resources/scripts/command/docker, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/gradle, scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/command/jenkins, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/command/node, scripts/src/main/resources/scripts/command/sonar, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/command/yarn, scripts/src/main/resources/scripts/functions
Implemented #641
That was a long day/night...
=> #641: use mirrors for managed tools

scripts/src/main/resources/scripts/command/java
=> #650: update java to 11.0.13_8

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
=> #669: fixed installation of custom tools

scripts/src/main/resources/scripts/command/eclipse
improvement for #538 from analysis of #674
=> #674: require confirmation to continue with wrong Java version

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
=> #665: devon ide update shall update all installed tools

scripts/src/main/resources/scripts/command/intellij
=> #680: fixed intellij download

scripts/src/main/resources/scripts/command/ide
=> #685: improve UX for update on win

scripts/src/main/resources/scripts/command/mvn
support for `MAVEN_ARGS` variable for mvn 3.x
=> support for MAVEN_ARGS variable for mvn 3.x

.github/labeler.yml, .github/workflows/label-pr.yml
=> added automatic PR labeling

documentation/LICENSE.asciidoc, documentation/cli.asciidoc, documentation/graalvm.asciidoc, documentation/scripts.asciidoc, documentation/variables.asciidoc, scripts/src/main/resources/scripts/command/graalvm, scripts/src/main/resources/scripts/command/ide
=> GraalVM integration

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
1. checkout the older devonfw (3.2.1) generated project from [sujith-mn/jwt-sample](https://github.com/sujith-mn/jwt-sample)
2. migrate it to the latest version devon java migrate
3. compile devon java compile
=> fixed the java migration issue.

scripts/src/main/resources/scripts/functions
#734 create doUnzip function
The following command in functions has to be changed to activate the doUnzip:
#doRunCommand "unzip -qn '${1}' -d '${target_dir}'"
doUnzip ${1} ${target_dir}
=> #734 create doUnzip function

scripts/src/main/resources/scripts/command/intellij
=> #717: fix intellij fails on update

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
=> #761: update devon4j to 2022.04.001

scripts/src/main/resources/scripts/functions
=> #765: fixed/reverted doReplaceExtractedSkipSingleFolder

.github/workflows/build-pr.yml, .github/workflows/build.yml, scripts/src/main/resources/scripts/functions, scripts/src/test/bash/test-setup
=> #687: fix git pull issues

scripts/src/main/resources/scripts/command/docker
small fix for #770
It only fixes most obvious bugs I ran into during VPNKit installation.
The bug #770 will not entirely get resolved by this PR.
It is just a small step further.
=> #770: first small fixes for VPNKit

scripts/src/main/resources/scripts/command/ide
=> #749: prompt default for settings URL

scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
Fixes #779 
Also fixes a bug from PR #778 / #655 using functions
=> #779: fix colors

scripts/src/main/resources/scripts/functions
=> #740: ask to continue if devon command fails

scripts/src/main/resources/scripts/command/sonar
update sonarqube to version 9.4.0.54424
=> update sonarqube to 9.4.0.54424

scripts/src/main/resources/scripts/functions
Fixed #803 and also corrects fix for #687.
=> #803: fix git pull on debug

scripts/src/main/resources/scripts/command/ide, scripts/src/main/resources/scripts/functions
=> #798: English grammar fix for success message

documentation/DoD.asciidoc
=> created definition of done 

CHANGELOG.asciidoc, documentation/docker-desktop-alternative.asciidoc, documentation/usage.asciidoc
=> #767 Fix AsciiDoc issues

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/environment-project, scripts/src/main/resources/scripts/functions
=> #848: auto update PATH on doDevonCommand

CHANGELOG.asciidoc, documentation/LICENSE.asciidoc, documentation/cli.asciidoc, documentation/devonfw-ide-usage.asciidoc, documentation/gh.asciidoc, documentation/scripts.asciidoc, scripts/src/main/resources/scripts/command/gh
GitHub CLI should be implemented and working correctly as of this writing
=> GitHub cli

CHANGELOG.asciidoc, documentation/LICENSE.asciidoc, documentation/cli.asciidoc, documentation/devonfw-ide-usage.asciidoc, documentation/quarkus.asciidoc, documentation/scripts.asciidoc, scripts/src/main/resources/scripts/command/quarkus
Implements issue #894.
I also made a PR for the mirrors: https://github.com/devonfw/ide-mirrors/pull/33.
=> #894: Integration of Quarkus CLI

documentation/gh.asciidoc, documentation/ionic.asciidoc, documentation/ng.asciidoc
I just found a typo in one of the tools documentation and I thought a quick check for more typos would make sense to make a pull request. That's all I found for now.
=> Tools Documentation Update

CHANGELOG.asciidoc, scripts/src/main/resources/setup.bat
=> #923: use quotes in setup.bat

scripts/src/main/resources/scripts/functions
=> #935: fast fail in doDevonCommand

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/devon.bat
Added delay expansion in `devon.bat` to fix a bug reported by a user. Therefore some variables were changed from `%VAR%` to `!VAR!`. 
Issue: https://github.com/devonfw/ide/issues/954
=> #954: Fixed devon.bat with delay expansion

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/eclipse
=> #986: fixed eclipse java detection

configurator/src/main/java/com/devonfw/tools/ide/migrator/Migrations.java
PR for devon4j 2022.12.001 Update to fix build
=> devon4j 2022.12.001 update

scripts/src/main/resources/setup.bat
=> #1017: simple fix for infinity loop

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/devon.bat, scripts/src/main/resources/scripts/functions, scripts/src/main/resources/setup.bat
=> #1020: windows error handling

scripts/src/main/resources/scripts/command/docker
=> #1006: Updating name of executable file

.github/workflows/test-ubuntu.yml, scripts/src/main/resources/scripts/command/eclipse, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/mvn, scripts/src/main/resources/scripts/devon, scripts/src/main/resources/scripts/functions
This PR fixes shellcheck errors and updates the installation of shellcheck on integration test for Ubuntu and CI Build. 
Related issue: #1049
=> #1049 : Fix shellcheck errors and update shellcheck version 

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/devon.bat
=> #1068: fixed devon.bat -v

scripts/src/main/resources/scripts/devon.bat
=> #1071: improved/fixed devon.bat setx PATH for empty user path

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/vscode
This PR fix the bug report for #1074.
=> #1074 :  Fix vscode plugin installation

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/command/intellij
fixes #1104 but will only work properly in combination with fix for #1080 (recent `ide-settings`).
=> #1104: fix intellij plugin installation

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/functions
=> #1098: workaround fix for devon node version set

documentation/pom.xml
=> #1110: update to latest docgen version to fix build issue

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/UpdateManager.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/eclipse/EclipseEclipseCrawler.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/intellij/IntelliJIntellijEditionCrawler.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/rancher/RancherCrawler.java
=> #1088: align editions in ide urls

url-updater/src/main/java/com/devonfw/tools/ide/url/model/folder/AbstractUrlFolder.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/GithubUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/JsonUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/MavenBasedUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/UpdateManager.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/WebsiteUrlUpdater.java
fixes #1127 by implementing error handling
=> #1127: error handling

CHANGELOG.asciidoc, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/eclipse/EclipseUrlUpdater.java
This PR adds milestone versions of eclipse e.g. `2023-06-M1`
Related issue: #1118
=> #1118: Add milestone versions of Eclipse

url-updater/src/main/java/com/devonfw/tools/ide/version/CharCategory.java, url-updater/src/main/java/com/devonfw/tools/ide/version/CharReader.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionComparisonResult.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionIdentifier.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionObject.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionPhase.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionSegment.java, url-updater/src/test/java/com/devonfw/tools/ide/version/VersionIdentifierTest.java, url-updater/src/test/java/com/devonfw/tools/ide/version/VersionSegmentTest.java
add code to parse, compare, validate and decompose versions
implicitly required for #1090
=> add code to parse, compare, validate and decompose versions

.github/workflows/update-urls.yml, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionComparisonResult.java
=> #1140: improve update URLs action

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/helm/HelmUrlUpdater.java
feature/#1156-Correct-wrong-version-numbers-for-helm
=> #1156-Correct-wrong-version-numbers-for-helm

scripts/src/main/resources/scripts/command/project
=> #1158: fix project git.branch feature

CHANGELOG.asciidoc, documentation/intellij.asciidoc, documentation/software.asciidoc, documentation/vscode.asciidoc, scripts/src/main/resources/scripts/command/intellij, scripts/src/main/resources/scripts/command/vscode, scripts/src/main/resources/scripts/migrations/2023.06.001
Addresses/Fixes: #1147 
Implements:
* changed plugin paths from software/x-plugin to plugins/x
* adjusted documentation
=> #1147: separate plugins from software

documentation/devonfw-ide-contribution-getting-started.asciidoc
fixed some typos in getting-started documentation
=> #1160: fix spellcheck issues

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/az/AzureUrlUpdater.java
=> #1181: fixed azure updater

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/docker/DockerRancherDesktopUrlUpdater.java
=> #1200: use *.msi downloads instead of *.exe for rancher on windows

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/eclipse/EclipseUrlUpdater.java
=> #1210: disable milestones

documentation/vulnerabilities.asciidoc
=> #1106: added vulnerabilties doc

scripts/src/main/resources/scripts/devon.properties
=> #1084: make rancher default edition

scripts/src/main/resources/scripts/functions, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/AbstractUrlFile.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/UrlChecksum.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/UrlDownloadFile.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/UrlFile.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/UrlSecurityFile.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/file/UrlStatusFile.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/folder/UrlEdition.java, url-updater/src/main/java/com/devonfw/tools/ide/url/model/folder/UrlVersion.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/UpdateManager.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionObject.java, url-updater/src/main/java/com/devonfw/tools/ide/version/VersionRange.java
bugfix for #1106 to handle security file in url-updater.
=> #1106: fix url-updater to properly handle security config file

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractProcessorWithTimeout.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java, url-updater/src/main/java/com/devonfw/tools/ide/url/updater/UpdateManager.java
improvement for #1162: consider timeout also in outer loop of UpdateManager
=> #1162: consider timeout also in outer loop of UpdateManager

scripts/src/main/resources/scripts/command/android-studio, scripts/src/main/resources/scripts/migrations/2023.07.001
Addresses/Fixes: #1259
Implements:
* changed android-studio plugins directory from software/android-studio-plugins to plugins/android-studio
=> #1259: changed android-studio plugins directory

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/docker/DockerRancherDesktopUrlUpdater.java
=> #1252: fixing Docker linux download link

url-updater/src/main/java/com/devonfw/tools/ide/url/updater/jasypt/JasyptUrlUpdater.java
=> #1231:added jasypt urlUpdater

scripts/src/main/resources/scripts/functions
=> #1287: always clone urls

scripts/src/main/resources/scripts/command/ide
=> #1285: remove renaming toolname mappings

documentation/functions.asciidoc, scripts/src/main/resources/scripts/command/docker, scripts/src/main/resources/scripts/command/java, scripts/src/main/resources/scripts/functions
removed obsolete `doResolveDownloadUrl` that is a leftover forgotten in #1084
=> #1084: removed obsolete function doResolveDownloadUrl

documentation/docker.asciidoc, scripts/src/main/resources/scripts/command/docker
=> #1252: #1279: completely reworked docker

documentation/software.asciidoc
#1186 install.asciidoc file referenced by software.asciidoc is missing
=> #1186 install.asciidoc file referenced by software.asciidoc is missing

CHANGELOG.asciidoc, scripts/src/main/resources/scripts/functions
=> #1297: remove doFail debugging leftover

documentation/migration-from-ide-2023.04.001.asciidoc
=> Correction of documentation

ide/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, ide/src/main/java/com/devonfw/tools/ide/context/IdeContextConsole.java, ide/src/main/java/com/devonfw/tools/ide/env/Environment.java, ide/src/main/java/com/devonfw/tools/ide/env/EnvironmentImpl.java, ide/src/main/java/com/devonfw/tools/ide/env/var/EnvironmentVariablesImpl.java, ide/src/main/java/com/devonfw/tools/ide/env/var/EnvironmentVariablesResolved.java, ide/src/main/java/com/devonfw/tools/ide/env/var/def/IdeVariables.java, ide/src/main/java/com/devonfw/tools/ide/log/IdeSubLogger.java, ide/src/test/java/com/devonfw/tools/ide/context/AbstractIdeTestContext.java, ide/src/test/java/com/devonfw/tools/ide/context/IdeContextTest.java, ide/src/test/java/com/devonfw/tools/ide/context/IdeSlf4jContext.java, ide/src/test/java/com/devonfw/tools/ide/log/IdeSlf4jLogger.java, ide/src/test/java/com/devonfw/tools/ide/log/IdeTestLogger.java, ide/src/test/resources/ide-projects/_ide/software/readme, ide/src/test/resources/ide-projects/_ide/urls/readme, ide/src/test/resources/ide-projects/basic/conf/ide.properties, ide/src/test/resources/ide-projects/basic/home/Downloads/ide/readme, ide/src/test/resources/ide-projects/basic/home/ide.properties, ide/src/test/resources/ide-projects/basic/home/readme, ide/src/test/resources/ide-projects/basic/readme, ide/src/test/resources/ide-projects/basic/scripts/ide, ide/src/test/resources/ide-projects/basic/settings/ide.properties, ide/src/test/resources/ide-projects/basic/setup, ide/src/test/resources/ide-projects/basic/workspaces/foo-test/my-git-repo/readme, ide/src/test/resources/ide-projects/basic/workspaces/foo-test/readme, ide/src/test/resources/ide-projects/basic/workspaces/main/readme, ide/src/test/resources/ide-projects/readme
For #1318 I ...
* wrote a JUnit
* improved test infrastructure
* fixed bugs
=> #1318: added JUnit with fixes + improvements

ide/src/main/java/com/devonfw/tools/ide/env/var/EnvironmentVariables.java, ide/src/test/java/com/devonfw/tools/ide/context/IdeContextTest.java
for #1318:
* added `EnvironmentVariables.getPath` method
* test it on `M2_REPO` including resolving of `~` to `HOME` directory.
=> #1318: added getPath method to get variable as Path + test

ide/src/main/java/com/devonfw/tools/ide/common/SystemInfo.java, ide/src/main/java/com/devonfw/tools/ide/common/SystemInfoImpl.java, ide/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, ide/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
adds support to detect OS and architecture for #1090
=> #1090: support to detect OS and arch

scripts/src/main/resources/scripts/functions
=> #1376 fixed typo
